# Generated by Django 3.2 on 2022-08-10 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0002_alter_bookitem_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField()),
                ('room', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BookItemPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.bookitem')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.place')),
            ],
        ),
    ]
