# Generated by Django 3.2 on 2022-08-10 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='room',
            new_name='name_room',
        ),
    ]
