# Generated by Django 3.2 on 2022-08-10 17:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('71bd94e1-f330-4269-bdff-bb2b22047817')),
        ),
    ]
