# Generated by Django 3.2 on 2022-08-10 18:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_bookitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('309e0aa4-fb87-4b10-a751-71335142d2cd')),
        ),
    ]
