# Generated by Django 3.2 on 2022-08-10 19:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_bookitem_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookitem',
            old_name='is_rent',
            new_name='is_loan',
        ),
        migrations.AlterField(
            model_name='bookitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('62839cc4-473c-47a3-b300-a2bb92fab5dd')),
        ),
    ]
